# Generated by Django 3.2.9 on 2021-11-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211123_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('V', 'Variável'), ('S', 'Simples')], default='V', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='promotional_price',
            field=models.FloatField(default=0.0, verbose_name='Preço de promocional'),
        ),
    ]
