# Generated by Django 3.2.9 on 2021-11-23 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(verbose_name='Preço Total')),
                ('status', models.CharField(choices=[('A', 'Aprovado'), ('C', 'Criado'), ('R', 'Reprovado'), ('P', 'Pendente'), ('E', 'Enviado'), ('F', 'Finalizado')], default='C', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Produto')),
                ('product_id', models.PositiveIntegerField(verbose_name='ID do Produto')),
                ('variation', models.CharField(max_length=255, verbose_name='Variação')),
                ('variation_id', models.PositiveIntegerField(verbose_name='ID da Variação')),
                ('price', models.FloatField(verbose_name='Preço')),
                ('promotional_price', models.FloatField(default=0, verbose_name='Preço Promocional')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('image', models.CharField(max_length=2000, verbose_name='Imagem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
            },
        ),
    ]
